### ISSUE TITLE
is it successful ? but when I reopen it ,it still not get pro?

### ISSUE THREAD

**Issue by DancingLeaf123** [arv-anshul/ColdTurkeyBlocker-Pro#1]
![image](https://github.com/arv-anshul/ColdTurkeyBlocker-Pro/assets/23498471/3876ce8d-d630-4de1-8850-7828d2bd33dd)

**Comment by queenbee234** [comment]
it is successful

**Comment by arv-anshul** [comment]
Hey, @DancingLeaf123 and @queenbee234 ! Please check whether the issue is resolved or not.
