### ISSUE TITLE
it seems not work in v4.4 anymore, I have run it but still not get pro.

### ISSUE THREAD

**Issue by DancingLeaf123** [arv-anshul/ColdTurkeyBlocker-Pro#2]
![image](https://github.com/arv-anshul/ColdTurkeyBlocker-Pro/assets/23498471/419365b1-171e-4c15-89ba-4050c7f791ab)

**Comment by chaukhoa97** [comment]
Same here, it seems they fix it at 4.4...

**Comment by arv-anshul** [comment]
Hey, @DancingLeaf123 and @chaukhoa97 ! Please check whether the issue is resolved or not.

**Comment by chaukhoa97** [comment]
The script freezes when after I enter "win". It seems to be running but it takes so long and nothing happens (30 min+) so I guess it doesn't work. I already run git bash with administrator privillege

**Comment by arv-anshul** [comment]
@chaukhoa97 Can you send the location of **Cold Turkey Blocker** path in your windows system?

I guess, the script doesn't works because I don't know the path of the app in windows. I have passed the path of application as `C:/ProgramData/Cold Turkey/data-app.db`, and I guess it is not true.

**Comment by chaukhoa97** [comment]
It's C:\Program Files\Cold Turkey

**Comment by chaukhoa97** [comment]
I do change the script my self for it to match the path in my machine but it still freezes. I also don't see a file `data-app.db` in my Cold Turkey folder

**Comment by arv-anshul** [comment]
Can you share the **list of files** the directory (`C:\Program Files\Cold Turkey`) contains?

**Comment by chaukhoa97** [comment]
Here it is 
![image](https://github.com/arv-anshul/ColdTurkeyBlocker-Pro/assets/70827148/d12f8b43-8c2f-4b06-82ac-da78836dc132)

**Comment by arv-anshul** [comment]
Hmm, I cannot figure out the solution in this way. Give me some time I will figure it out soon with my friend's laptop.

**Comment by arv-anshul** [comment]
Hey, I am not able to navigate in windows for this solution. If possible, try finding the path in your system to solve this issue and create a PR for that.

@chaukhoa97
#1

**Comment by chaukhoa97** [comment]
Hey I do find the path of the `data-app` file: "C:\ProgramData\Cold Turkey\data-app.db" but when I manually change the script it still freeze, I do switch between `\` and `/` but the result was the same...
