### ISSUE TITLE
Windows version does not work

### ISSUE THREAD

**Issue by ErayOzcanUCLL** [arv-anshul/ColdTurkeyBlocker-Pro#5]
I have tried using the command you wrote:
```
python <(curl -sSL https://raw.githubusercontent.com/arv-anshul/ColdTurkeyBlocker-Pro/main/main.py)
At line:1 char:8
+ python <(curl -sSL https://raw.githubusercontent.com/arv-anshul/ColdT ...
+        ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

```
i have tried manually putting the script contents in a python script and running it myself but that also doesnt seem to turn it into a pro version even if i get no errors

**Comment by arv-anshul** [comment]
Hey, @ErayOzcanUCLL I don't have Windows PC thats why you guys are facing these issue. I have tried to solve the errors but I can't. 😞

**Comment by quantumxx** [comment]
@ErayOzcanUCLL Just used it on Windows, and it works. You can just download the script from the direct link and then run it through python. 
![image](https://github.com/arv-anshul/ColdTurkeyBlocker-Pro/assets/138307343/d7f10628-dd5c-4323-b0e9-25f8f8cc1dd8)

**Comment by quantumxx** [comment]
Can I update the instructions for the Windows version with a pull request?  @arv-anshul
